language: node_js
node_js:
  - "4.3"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
before_script:
  - npm install -g bower
  - npm install -g gulp
  - bower install
  - gulp build
script: gulp test
